name: deploy
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:   
    - uses: actions/checkout@master
    - run: sudo apt update && sudo apt install asciidoctor
    - run: make all
    - name: the_deployment
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod --dir=./dist/
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}